/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muxi_lfernandosantos_desafiomuxi_Converter */

#ifndef _Included_com_muxi_lfernandosantos_desafiomuxi_Converter
#define _Included_com_muxi_lfernandosantos_desafiomuxi_Converter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muxi_lfernandosantos_desafiomuxi_Converter
 * Method:    converterToReal
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_muxi_lfernandosantos_desafiomuxi_Converter_converterToReal
  (JNIEnv *env, jobject obj, jdouble price){

    return price * 3.5;
  }

#ifdef __cplusplus
}
#endif
#endif
